-- Migration: Add ai_generated field to proposal_questions table
-- Created: 2024-11-17
-- Description: Adds ai_generated boolean flag to track AI-generated answers

-- Add the ai_generated column with default value False
ALTER TABLE proposal_questions
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE;

-- Add comment for documentation
COMMENT ON COLUMN proposal_questions.ai_generated IS 'Flag indicating if the answer was generated by AI';

-- Update existing records (all existing answers are assumed to be human-generated)
UPDATE proposal_questions
SET ai_generated = FALSE
WHERE ai_generated IS NULL;

-- Optional: Create index if you'll be filtering by AI-generated answers frequently
CREATE INDEX IF NOT EXISTS idx_proposal_questions_ai_generated
ON proposal_questions(ai_generated);

-- Verify the migration
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'proposal_questions'
  AND column_name = 'ai_generated';
